spring:
  profiles:
    active: local

server:
  port: 9090
  api:
    listen:
      host: 0.0.0.0
      port: 3003
camel:
  component: jetty

  springboot:
    main-run-controller: true
    name: easy-client-adapter
    stream-caching-enabled: true

easy:
  mfi-name: MC EASY MICROFINANCE CO. LTD.
  mambu:
    host: mceasy.sandbox.mambu.com/api
    username: mojaloop
    password: Juan1234

#informed through runtime variable (java -Doutbound.endpoint=http://localhost:4001)
outbound:
  endpoint:  http://localhost:4001